### ISSUE TITLE
Nothing displayed with Google Chrome Version 48.0.2564.109 m

### ISSUE THREAD

**Issue by ViktorReib** [ffacon/tapestry5-angular-demo#5]
After i try to start the application with "mvn jetty:run", im surprised to see a blank page.
Tapestry any times redirect my to the URI "http://localhost:8080/web#/phones".

**Comment by ffacon** [comment]
As mention in the ReadMe the correct URL to this demo is http://localhost:8080/#/phones. 
Did you try to hit this URL directly?

**Comment by ViktorReib** [comment]
Sure, i get always redirected to http://localhost:8080/web#/phones. Demo works fine with FIrefox and IE.

**Comment by ffacon** [comment]
Strange! There is no default page defined in this demo. I guess that /web should come from your history.
